dist: trusty
sudo: required
services:
- docker
language: go
go:
- 1.16.x
script:
- go mod vendor
- make testacc
- make vet
- make build
- make website-test
branches:
  only:
  - master
matrix:
  fast_finish: true
  allow_failures:
  - go: tip
install:
- bash scripts/gogetcookie.sh
env:
  global:
  - secure: ddtMWzF3IQcYqNvCdHQtEGkEOWFIh+UQVlDoH8qqLSNjlmb6Llu02OtUddOdlpG+ZhuTTyewoBfHl5i+gC+iaJ0xmN44IMOgVzBQrmVjqlmwT0G37yUKMzDK+Q0UCOa3K0nwxB636WjNRwmrawQ2v7s17oL/oCia04Eqc/ONNb+UkJ2QoPvUTcJLnGPn3QkiuUvpId0YCHBClf/x5TwcpAMBRLpwCaY13zT+0JQ+sQgdA3ITaR0y1Zu6eRBV+eKJsXJwgsp2uuF/CpzSmS7SkWdZ3IG3Cra3i/RogNDG8MFfZ7bs4rYClPBGP+9RfMqjHgtFEbmwb6I/Ht9FLQCHOmMNOfwd/jp6bebEk2XD6b2mP/4MzZ7wE9jaF7EocpVkduPpfG6p4caZ0pLf7Co4Hz8mGDWtcO5xIL8pcpsCG4hL+KHHurHN7UnjWytshE3BDoFJqOn29oOUNddPNOO0JUe0JXq/ZxsQjuf6Ew0eUC5f6/y4fGM+IRd3Qwx1Js8ayRJLG2dBRqsroR/22n7Obq4QWkJL2RsxzWogbRt5CgjhpBCNPcz67ycwXNNFHzJJ7TFE4r7/kd6SNT3TmIy97fk+IYf/z6PsG5KIKqEWuMXnsKtYx+SB3PfPiitCbHK0kyZPDnFfPrvkf/sH8vQipo5gJXf7RpJHH4YybKP5nWA=
  - secure: UGjV7Xc4bL9Mth3zMO6CKbSR9SC0Vm4Vp3GmrwIKiymxFwTRZSlXlpErhXrfsa2CwtK23WrXkP2lxYKrrdmXwO74Fi3StoXpf0fH5uhNII1WxaxTB+sXFphW4Bjru5SoSkaux7unlWA4474MNdOz4FjAZ/t8po9JNu7CHzX6ylkONy2rbgk6E+swq/R0Buey1r5bvtcvbzmb5WscOLW169C2czm82om0aByzZt4JvaSNl55wxrYmyunA91ejzkwVzW8gZRgy1gWND4L056wu86erpbT1Nsc5NThYwulXZICLiEIQUJ+lmJWw/vjRYBn3U+79EkFNgGm7q3FPL7m+YjoTgyyGTbT/U5EWmAYb+8/A7wkBQa1KOKQAumodJiURT4MtkWOo+c/ZcqTmzD8cQWUnUJZUBC6C5gy0KsgGplAOHGJdLcJKZEI1+uYdKdoo/Y9kmsNRmJ6vvupethaGiJX2BTCj9V/iS11F0vDyx+P7JDEaO5bSagB8Hlz96fLuh/e5aycU31wT590aHaCWakrJMeqRWSbgrNVCWb1ySOj6FxG7kRFj2tQ6MEYx6jgG7ZimMK0NGKIS2ys6EF8BicXTJqxhNwHo2gE5BtGYu6+L5d4GIatVWgrpqagsbrG1m8f41wSRA5P4+Kpr4t1tyIpyjTFZfS7K+CdMUNZevRE=
  - secure: Gx2b0uYVPWrBsQVFscJqeCOy0HhGcSq3CPs14n7SKf58EXKYxep8GLr9GrNVUDp6De2RXbt/BOiJYr6gfNvWGfjgau8TIg7jeHJPdQOh8BoMg5idJ9ii653eXy2xuPrAO/ezbTt8eGVMU7LaNwY39fhzeqvZHoDaEHqEmfroAYHsmcM9w9KJB+y1RF5endCBhc8+6Nz4U26lIJ/au3SWy7ku7rxwhWZCVHFu85lur3epP6lbyz3YKI3b0dTBB+eT/eyPR6+sbnBTCMnBcg6iCIgDkAdRK8nsD8PiFfnororFfjEQ2y0o/6u7pThubi7iRXsIyRr6iWWoRoQysLTMy0viJOVMy0iEshemKldgWKVAcdZFqnMw5xuEolKtSTVoNxCqSeZRzRgTcJqP3jGq9r5kSB1XUhcbbX5kl7tKTMzUHj2rPXnT0NgPeTlIb7S0JV3o35HCxI9tsCK0p7b1L08tGGQgEctJCb7CErYo8ZmB3JtCXnngXUd95V+ti7YLZdRQao0jOngVxyDBomMzzDak7eRwSgFEPHzLIGmxgdpT1lHCk810tm+a1UQWYxjVJlt7iqrDuF7N+8CvNym9+/NQRW8X9Isvh7lQ/RufQ5Q4eWn6/avKOmN0Kgr1w13DuNVyXXb0+uYNroGLgXrlsgFDWl88C6Fj6vO7oUvbKvk=
