name: Acceptance Test Schedule

# Runs acceptance tests on a cron schedule

on:
  schedule:
    - cron: 0 14 * * MON-FRI # Every weekday at 14:00 UTC (10a Eastern)

concurrency: acceptance_tests

jobs:
  acceptance:
    # Runs the acceptance test suite using the `Acceptance Tests` environment.
    # The enviroment should be configured to require reviewers approve the
    # step. This allows the tests to be added as a check to PRs.
    #
    # This job has the `continue-on-error` set to true which prevents blocking
    # PRs if the tests fail.
    needs: unit
    runs-on: ubuntu-latest
    environment:
      name: Acceptance Tests

    concurrency: acceptance_tests

    continue-on-error: true

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x

      - name: Checkout
        uses: actions/checkout@v2

      - name: Go Mod Vendor
        run: go mod vendor

      - name: Go Mod Tidy
        run: go mod tidy
        
      - name: make testacc
        run: make testacc
        env:
          TESTARGS: -parallel 20
          ZPA_CLIENT_ID: ${{ secrets.ZPA_CLIENT_ID }}
          ZPA_CLIENT_SECRET: ${{ secrets.ZPA_CLIENT_SECRET }}
          ZPA_CUSTOMER_ID: ${{ secrets.ZPA_CUSTOMER_ID }}
